# Generated by Django 2.1 on 2018-10-08 13:35

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_max', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('exp_max', models.IntegerField(default=100)),
                ('current_exp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.CharField(default='404.png', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerSql', models.CharField(max_length=2500)),
                ('usedPrompt', models.BooleanField(default=0)),
                ('note', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('rated', models.BooleanField(default=0)),
                ('completed', models.BooleanField(default=0)),
                ('closed', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StageStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('databaseSql', models.CharField(max_length=5000)),
                ('complete', models.BooleanField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Stage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StageTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2500)),
                ('content', models.CharField(max_length=2500)),
                ('title', models.CharField(default='Zadanie', max_length=120)),
                ('points', models.IntegerField(default=5)),
                ('exp_points', models.IntegerField(default=20)),
                ('sampleAnswer', models.CharField(max_length=2500)),
                ('prompt', models.CharField(max_length=2500)),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence', models.BooleanField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Stage'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.StageTasks'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.StageTasks'),
        ),
    ]
