# Generated by Django 2.0.3 on 2018-04-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('pesel', models.CharField(max_length=11, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievementId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Achievement')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerSql', models.CharField(max_length=2500)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StageStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('databaseSql', models.CharField(max_length=5000)),
                ('stageId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Stage')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Account')),
            ],
        ),
        migrations.CreateModel(
            name='StageTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('stageId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lecturerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2500)),
                ('points', models.IntegerField(default=4)),
                ('sampleAnswer', models.CharField(max_length=2500)),
                ('stageTaskId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Task'),
        ),
        migrations.AddField(
            model_name='achievementtask',
            name='taskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Task'),
        ),
    ]
