# Generated by Django 2.1 on 2018-09-18 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='note',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
