# Generated by Django 2.1 on 2018-10-09 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.AddField(
            model_name='answer',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 0, 59, 23, 526818)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.StageStudent'),
        ),
        migrations.AlterField(
            model_name='stagestudent',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 17, 0, 59, 23, 526317)),
        ),
        migrations.AlterField(
            model_name='stagestudent',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 0, 59, 23, 526317)),
        ),
        migrations.AlterField(
            model_name='userabsence',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 0, 59, 23, 524815)),
        ),
    ]
