# Generated by Django 2.1 on 2018-09-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='pesel',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='second_name',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='current_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='current_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='exp_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='hp_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
