# Generated by Django 2.1 on 2018-09-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20180918_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='picture',
            field=models.CharField(default='404.png', max_length=250),
        ),
    ]
