# Generated by Django 2.1 on 2018-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_achievement_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetasks',
            name='content',
            field=models.CharField(default='Lorem ipsum', max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagetasks',
            name='propmpt',
            field=models.CharField(default='Lorem ipsum', max_length=2500),
            preserve_default=False,
        ),
    ]
