# Generated by Django 2.1 on 2018-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20180927_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='usedPrompt',
            field=models.BooleanField(default=0),
        ),
    ]
