# Generated by Django 2.1 on 2018-09-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_answer_usedprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.Stage'),
            preserve_default=False,
        ),
    ]
