# Generated by Django 2.1 on 2018-10-24 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20181024_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesanswer',
            old_name='massage',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='answer',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 3, 49, 15, 842825)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 3, 49, 15, 845332)),
        ),
        migrations.AlterField(
            model_name='stagestudent',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 3, 49, 15, 841822)),
        ),
        migrations.AlterField(
            model_name='stagestudent',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 3, 49, 15, 841822)),
        ),
        migrations.AlterField(
            model_name='userabsence',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 24, 3, 49, 15, 839819)),
        ),
    ]
