# Generated by Django 2.1 on 2018-11-09 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20181024_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='delete_for_from_user',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='delete_for_to_user',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 20, 38, 59, 208277)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 20, 38, 59, 210784)),
        ),
        migrations.AlterField(
            model_name='stagestudent',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 20, 38, 59, 207775)),
        ),
        migrations.AlterField(
            model_name='stagestudent',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 20, 38, 59, 207775)),
        ),
        migrations.AlterField(
            model_name='userabsence',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 9, 20, 38, 59, 206271)),
        ),
    ]
