# Generated by Django 2.1 on 2018-09-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_answer_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagetasks',
            old_name='propmpt',
            new_name='prompt',
        ),
    ]
