# Generated by Django 2.1 on 2018-09-27 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20180928_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rated',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='stagetasks',
            name='difficulty_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
