INSERT INTO viking.`models_stage`(`name`) VALUES ("Nowicjusz"),("Normalny"),("Wysoki"),("Ekspert"),("Mistrz"),("Udręka");

INSERT INTO viking.models_difficultylevel (level,title) VALUES (1,'Zadanie 1'),(2,'Zadanie 2'),(3,'Zadanie 3'),(4,'Zadanie 4'),(5,'Zadanie 5');

INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('List','Za górami, za lasami żył sobie Bjorn. Pewnego zimnego ranka obudziło go stukanie w okno. Po paru chwilach, gdy w końcu udało mu się otworzyć oczy, zobaczył Drozda z liścikiem w dziobie. Wystraszył się, że to kolejne pismo od komornika. Po otwarciu koperty zobaczył to … „Przyjeżdżam za 6 tygodni, mam nadzieje, że przygotujesz dla mnie cos dobrego… - TEŚCIOWA.”',1,1);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Panika','Bjorn ze strachu przed swoja teściową zaczął pakować wszystkie potrzebne i niepotrzebne rzeczy. Zastanawiał się długo, gdzie mógłby się przed nią schować. W końcu przyleciał drozd radząc, by wiał gdzie pieprz rośnie.',2,1);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Niespodzianka','Bjorn postanowił zostawić małą niespodziankę swojej teściowej. Wiedział, że ta nie wytrzymałaby bez zaglądania do spiżarni, gdzie trzymał jej ukochany bigos, dlatego do każdego słoika dodał po kilka papryczek chili. W taki sposób teściowa posiadła umiejętność ziania ogniem.',3,1);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Koszmar','Po długim marszu Bjorn i Drozd, postanowili uciąć sobie drzemkę pod drzewem. Przyśnił mu się dzień, w którym niespodziewanie odwiedziła go teściowa. Z hukiem wpadła do chatki, domagając się obiadku. Wyczyściła mu z bigosu całą spiżarnię, a Bjorn tylko biegał z garem, żeby dać jej dokładkę. Niestety, niechcący albo chcący wpadł mu do kotła czosnek. Staruszka zaczęła się dusić, bo okazało się, że jest na niego uczulona. Po przebudzeniu olśniło Bjorna i udał się na pobliskie pole z czosnkiem, aby w razie czego mieć coś do obrony.',4,1);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Ucieczka','W celu zebrania załogi na swój statek, Bjorn chodził od chatki do chatki prosić innych ludzi, aby zgodzili się na wspólną ucieczkę. Mało kto chciał otworzyć mu drzwi, bo bali się, że Teściowa, która jest postrachem nie tylko Bjorna, ale też całej wioski – wcześniej przyjechała. Jednak przyjemny odgłos ćwierkania Drozda pozwolił im uwierzyć, że to nie to, o czym myślą. Po wysłuchaniu próśb biednego wikinga, zgodzili się towarzyszyć mu w wyprawie. Wszyscy razem udali się do portu, gdzie zaczęli wspólną przygodę',5,1);


INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Cicha woda','Po wielu tygodniach bujania się po morzu w wielkim skwarze bez najmniejszego podmuchu wiatru, który muskałby ich brody, zorientowali się, że kończą im się zapasy wody, a co najgorsze, od tygodnia nie mieli w ustach czegoś mocniejszego. Wikingowie, jako naród żyjący wśród śniegu nie są przyzwyczajeni do słońca, dlatego też strasznie cierpieli w upale i zaczęli coś majaczyć.',1,2);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Syrenka','Następnego ranka na horyzoncie ujrzeli skałę, a na niej postać kobiety. Wszyscy co do jednego chwycili za wiosła i zaczęli gnać w jej stronę. Gdy podpłynęli trochę bliżej zobaczyli, że to piękna syrena, kusząca ich swoim głosem. Wikingowie nie mogąc oprzeć się tej niewiaście, siedzieli oparci o burtę z jęzorami na wierzchu i śliną cieknącą po brodzie. Drozd przyglądał się im z góry dłuższa chwilę, po czym rzekł: „Księga Wikingów mówi jasno: Kto się w syrenie zakocha, temu morze strzeli focha!”, lecz nikt go nie słuchał, więc odwrócił się do nich ogonem i odleciał.',2,2);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Przechyły','Wszyscy jeszcze oszołomieni widokiem syreny nie zauważyli, że zaczęło coraz bardziej bujać statkiem. Jedni kładli się sądząc, że przechyły będą mniej odczuwalne, inni trzymali się masztu, bo uznali go za dobre miejsce, a reszta załogi dzielnie sterowała statkiem, aby płynąć ciągle przed siebie i jak najszybciej uciec od wrednej kobiety – TEŚCIOWEJ.',3,2);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Wąż Loko','Po kilku dniach ciągłej walki z wiatrem, jedni zrobili się zieloni na twarzy i zaczęli farbować wodę, drudzy nadal trzymali się masztu coraz bardziej trzęsąc portkami, a cała reszta z Bjornem na czele dzielnie prowadziła łajbą. Aż tu nagle, ni z gruchy ni z pietruchy obok nich wynurzył się dziwny stwór. Długi był na 100 metrów, do węża bardzo podobny, ale na łbie miał potężnego irokeza. Bjorn spytał go: „Kim jesteś i gdzie znajdę jakiś ląd?”, po czym ten odpowiedział: „Loko mówią mi, a ląd wiele mil ssssstąd jesssst”, po czym zanurzył się ochlapując wszystkich i odpłynął w nieznane.',4,2);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Sztorm','Po rozmowie z wężem Lokiem na niebie zebrały się czarne chmury. Wtedy już cała załoga zaczęła panikować i miała pełne gacie. Jedynie Bjornowi pozostały resztki rozumu i krzyknął do załogi: „Czego się bardziej boicie – podmuchu wiaterku, czy oddechu teściowej?!” Wtedy wszyscy bez chwili namysłu ruszyli dalej. Wpłynęli w wielką burzę, miotało nimi jak szatan na lewo i prawo, aż w końcu fala zepchnęła ich na skałę i cała łódź poszła w drzazgi. Bjorn w ostatniej chwili złapał ocalałą deskę i próbował dostrzec resztę swojej załogi. Niestety, nikogo nie zobaczył. Jedynie w oddali słyszał słowa Drozda „BJORN come back, come back…”',5,2);

INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Rozbitek','Bjorn wyrzucony przez morskie fale, leżał nieprzytomny na plaży. Obudziło go stukanie Drozda w jego hełm. Otworzył oczy i ujrzał przyjaciela, który powiedział do niego „Stary, Tobie to dać stery …” Bjorn nie pamiętał nic z tego, co się wydarzyło poprzedniego dnia. Drozd opowiedział mu o całym zdarzeniu, bo w momencie  gdy opuścił załogę, aby szukać najbliższego lądu, wracał na statek, żeby powiedzieć wikingom o swoim odkryciu i wtedy zobaczył, jak rozbijają się o skałę.',1,3);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Kokos ?','Wygląd wyspy, na której się znaleźli zdziwił ich, ponieważ była ona całkiem inna niż te w miejscu ich zamieszkania. Bjorn poczuł, że coś go kłuje w plecy. Wyglądało to jak duża, brązowa włochata kulka. Nie wiedział co to jest, ale pomyślał, że jak będzie z tym chodzić i do tego czegoś mówić, to w końcu coś się wykluje. Na chwilę zapominając o tym, co znalazł, zaczął wzywać pomoc. Po kilku godzinach nadal nikt go nie usłyszał, dlatego ze złości wziął swoje „jajo” i rzucił nim o palmę. Magiczna kulka rozpadła się, ale uderzenie było tak silne, że z palmy spadło kilka nowych. Bjorn podniósł rozbitą kulkę. Pięknie pachniała, więc spróbował ją zjeść. Postanowił, że nazwie to kokos i zrozumiał, że dzięki nim będzie miał pożywienia na wiele dni.',2,3);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Hamak','Bjorn stwierdził, że nie ma zamiaru już spać na kokosach, więc udał się do dżungli, aby znaleźć gałęzie i liany na hamak. Nagle przypomniał sobie, że zgubił swój topór, więc zębami twardymi niczym skała łamiąca statek utnie potrzebne mu materiały. Długo się męczył, poprosił też drozda o pomoc w dziobaniu drewna i w końcu udało się. Bjorn rozwiesił sobie hamak między dwiema palmami i zasypiając myślał o tym, co go czeka jutro.',3,3);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Złota rybka','Dobrobyt uderzył Bjornowi do głowy i jak już ma ekskluzywny hamak, to przecież nie będzie się żywić samymi kokosami. Postanowił więc ponownie udać się do dżungli, aby znaleźć coś, z czego mógłby wykonać wędkę. Pełen doświadczenia z poprzedniego dnia uwinął się z tym raz dwa . Wrócił na swoją plażę, ale złowić rybę nie było wcale tak łatwo. Na początku mu nie szło, ciągle łowił stare deski, buty i staniki. Aż w końcu po podniesieniu wędki przeżył szok. Jego oczom ukazała się złota rybka. Powiedziała, że może spełnić jego 3 życzenia. Bjorn nie mógł uwierzyć, więc odparł: „No to zrób tak, żeby Drozd miał różowy ogon”. Przez chwilę nic się nie działo, aż tu bach! Różowe pióra! Bjorn pomyślał, że ja może mieć wszystko co chce, to mógłby odzyskać swój toporek. Rybka go wysłuchała, broń spadła z nieba i uderzyła go w łeb, tym samym powalając go na ziemię. Drozd pochylił się nad nim i szyderczym głosem powiedział : „HA! To za te pióra!”',4,3);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Twardy sen','W czasie, gdy Bjorn leżał jak zabity, rybka wykorzystała okazję i uciekła. Drozd strasznie wkurzył się na swojego towarzysza i tym razem postanowił go nie budzić i pozostawił go leżącego na plaży w pełnym słońcu, żeby smażył się jak kotlet na patelni.',5,3);

INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Skwarek','Po całym dniu leżenia nieprzytomnie na słońcu, Bjorn był czerwony jak rak. Po podniesieniu się, wiking zobaczył swój ukochany toporek i z wielką radością zaczął skakać i dziko tańczyć. Poczuł jednak, że wszystko go piecze, więc wskoczył do morza, przy czym rozniósł się charakterystyczny dźwięk „tsssss…”. Wtem nagle wynurzył się wąż Loko i ze zdziwieniem odparł: „eee to tylko wy, myśśśślałem, że to moja sssstara…”, po czym odpłynął. Bjornowi zrobiło się lżej po kąpieli i wrócił na ląd.',1,4);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Dymek','Bjorn z Drozdem wylegiwali się na hamaku w cieniu palm, gdy nagle pojawiły się dziwne chmury. Po chwili zastanowienia doszli do wniosku, że to musi być dym. Pochodził on drugiej strony wyspy. Przyjaciele i tak nie mieli nic do roboty, więc wzięli kokosy na drogę i ruszyli w kierunku dziwnego zjawiska. Były dwie opcje: pożar, który może ich zabić, lub wyspa jednak nie jest bezludna.',2,4);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Pieprz','Po kilku godzinach walki z krzakami, dotarli na wielkie pole. Podeszli bliżej i zobaczyli, że na krzakach rosną dziwne czarne kuleczki. Bjorn po miłych doświadczeniach z kokosami postanowił sprawdzić, jak to smakuje. Niestety zaczął kaszleć, prychać i kichać. Przypomniał sobie, że dodawał trochę tego do bigosu, ale nigdy tak naprawdę nie wiedział dlaczego. Oboje stali zamyśleni, a nagle Drozd wybuchnął śmiechem i krzyknął: „HA! Zwialiśmy tam, gdzie pieprz rośnie!”',3,4);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Dziadek','Gdy fascynacja pieprzem minęła, spostrzegli dym, do którego chcieli dojść. Znajdował się on na końcu wielkiego pola. Przeszli przez pieprzowe krzaki ciągle kichając, aż w końcu dotarli do małej chatki. Zapukali, a z domku wybiegł dziadek, który celował do nich z procy nabitej pieprzem. Starzec miał wielkie oczy i nos oraz czoło wjeżdżające na potylice (zakola :)). Po krótkiej rozmowie z nim dowiedzieli się, że on również uciekał wiele lat temu od swojej teściowej gdzie pieprz rośnie. Po kilku godzinach gadania, Bjorn zapytał dziadka z ciekawości, dlaczego ma takie wielkie oczy. Ten odparł mu na to, że musi dobrze widzieć intruzów na swoim polu. Bjorn z jeszcze większym zainteresowaniem zapytał: „A dlaczego masz taki duży nos?” – ten śmiejąc się odparł – „A to przez ciągłe kichanie od pieprzu.”',4,4);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Zła nowina','Cała trójka rozmawiała ze sobą do późnej nocy o wszystkim i niczym. Dziadek przypomniał sobie, że w ostatnim czasie na wyspie działo się coś dziwnego. Opowiadał im o tym jak wulkan zaczął sobie popierdywać, pogoda zrobiła się kapryśna jak baba, a pieprzowe krzaki zaczęły więdnąć. W tym momencie staruszek zaczął trząść się ze strachu i rozpoczął opowiadać o tym, jak szedł sobie w nocy do wychodka, a tu nagle zobaczył jakąś postać w krzakach, w której okularach odbijał się księżyc i przypomniał sobie o wieczorach, kiedy światło lampki odbijało się od szkieł teściowej w podobny sposób. Dziadek powiedział, że po tych wydarzeniach niebezpiecznie jest chodzić po nocy, więc zaproponował im żeby zostali na kilka kolejnych dni.',5,4);

INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Spisek','Po kilku dniach mieszkania z dziadkiem, Bjorn wyszedł pozwiedzać trochę okolicę. Usłyszał jakieś dziwne głosy, krzyki i ryki, które brzmiały znajomo. Nie zastanawiał się długo co to mogło być, tylko od razu uciekł do ich kryjówki. Opowiedział towarzyszom o tym co się stało. Drozda nagle olśniło. Poskładał wszystkie fakty w całość i okazało się, że bardzo prawdopodobnie teściowe mają spisek i próbują odnaleźć zięciów.',1,5);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Trudna decyzja','Mężczyznom nawet nie przyszło do głowy, żeby spotkać się z treściową. Mówili jaka to ona zła, jak im życie zmarnowała i najchętniej wymazaliby ją z pamięci. W chatce czuli się bezpiecznie i nie chcieli jej opuszczać. Drozd nie mógł już tego słuchać i starał się namówić ich, aby jednak stawili jej czoła. Zapytał, czy zamierzają żyć w ciągłym strachu, czy iść do niej, załatwić sprawę po męsku. Ostatecznie, po namowach Drozda podjęli decyzję o podróży.',2,5);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Misterny plan','Przyjaciele nie wiedząc co robić, siedzieli zamyśleni przy stole. Po chwili Drozd wskoczył na stół i powiedział: „Gdy teściowa zły humor ma, to wtedy bigos na nic się zda”. Następnie opowiedział , jak można zwabić, ją pięknym zwierzęcym futrem.',3,5);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Pułapka','W końcu po wielu namysłach, postanowili wyruszyć w stronę pieczary teściowej. Bjorn zakłopotany myślą o spotkaniu ze staruszką, powiedział do Drozda: „Ani mi się śni rozmawiać z nią gdy jest na wolności!” Pomyśleli, że mogliby ją schwytać, więc zaczęli szukać potrzebnych materiałów.',4,5);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Tchórz','Na niebie były już gwiazdy, gdy dotarli pod pieczarę teściowej. Rozejrzeli się i na szczęście nie było jej w środku. Ukryli się w krzakach, aby przemyśleć dokładnie plan działania. Dziadziuś zaczął dygotać ze strachu i oznajmił im, że nie może iść z nimi dalej, tłumacząc to tym, że mógłby dostać zawału na widok teściowej. W ramach przeprosin podarował Bjornowi swoją procę z pieprzem. Drozd także postanowił opuścić przyjaciela mówiąc, że tylko on może pokonać teściową. Dał mu swoje różowe pióro na szczęście i życzył powodzenia.',5,5);

INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Dziura','Bjorn niepewnym krokiem udał się w stronę pieczary. Jeszcze raz się upewnił, że nie ma w środku teściowej, po czym zaczął szybko kopać dziurę. Gdy była już gotowa przykrył ją liśćmi, a futro ułożył obok pułapki. Aż tu nagle, usłyszał kroki teściowej. Szybko schował się za pobliskie drzewo, aby obserwować sytuację.',1,6);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Futro','Coraz bardziej było słychać kroki teściowej, aż w końcu Bjorn wychylając się zza drzewa, zobaczył ją. Staruszka, wracając do swojej pieczary, dostrzegła piękne futro leżące na ziemi i zaryczała: „Muuuuuuszę to mieć!” Zaczęła biec w jego stronę, a ziemia trzęsła się tak, że aż biedny wiking zaczął podskakiwać. W końcu wpadła w pułapkę Bjorna i krzyknęła tak głośno, że staruszek siedzący w krzakach osiwiał, a Drozd stracił wszystkie pióra.',2,6);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Spalony','Bjorn nie odważył się od razu porozmawiać z teściową, więc postanowił poczekać do rana. Kiedy pokonał strach, podszedł do dziury i cieniutkim głosikiem powiedział „Hop hop, nic mamusi nie jest?” Wtedy ta zionęła ogniem w jego stronę, przypalając mu brodę, Bjorn strasznie się zezłościł, bo bardzo kochał swoją rudą brodę i strzelił pieprzem w jej oczy.',3,6);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Salwa śmiechu','Teściowa na chwilę oślepła po celnym strzale Bjorna. Wykorzystał on okazję, wskoczył do staruszki i zaczął ja gilgotać w stopy piórkiem drozda. Nie wytrzymując ze śmiechu, zaczęła się trząść jak galareta i kazać mu przestać. Bjorn odpowiedział, jej „Przestanę, jak obiecasz mi, że już nigdy nie tkniesz mojego bigosu”. Teściowa nie mając innego wyboru, od razu zgodziła się.',4,6);
INSERT INTO viking.models_storylevel (title,content,difficulty_level_id,stage_id) VALUES ('Happy End','Zaniepokojeni ciszą Staruszek z ptakiem wybiegli ze swojej kryjówki, aby zobaczyć co się dzieje. Gdy Drozd zobaczył ich razem uśmiechnął się i powiedział: „ A morał z tej bajki jest krótki i niektórym znany: gdy teściowa swój nos wtyka, tylko bigos jej usta zamyka!',5,6);

INSERT INTO viking.models_achievement(name, points, description, picture) VALUES 
	('Medal precyzja Odyna', 5, 'Medal przyznawany za 100% punktów z zadania','medal_precyzja.png'),
	('Szybkie kopytko', 5, 'Medal przyznawany za najszybszą odpowiedź','medal_speed.png');